### ISSUE TITLE
Error on starting SP HA node on containerized environment

### ISSUE THREAD

**Issue by dilini-muthumala** [wso2/carbon-analytics#1203]
**Description:**
Seeing this error on server startup; this is not observed locally.

This can be reproduced locally if we shutdown both the nodes in the cluster at the same time; and then starting the nodes again with different node IDs (node ID as in wso2.carbon>id in deployment.yaml file) . 

### Cause:
Everytime a node joins a group, it creates an entry in CLUSTER_NODE_STATUS_TABLE table and periodically the cluster coordinator removes dead nodes from this table. 
As we start up 2 nodes those nodes create 2 entries in the same table. In addition to this, one node becomes cluster 'coordinator' (in carbon coordination terms) and the other becomes a 'member'. 
When we shutdown one node, usually, the coordinator makes sure to remove the dead node's entry from the table. This clean up happens periodically. When we shutdown both nodes at once, coordinator does not get a chance to clean up CLUSTER_NODE_STATUS_TABLE. Hence next time we bring up the servers, two entries will be there in the CLUSTER_NODE_STATUS_TABLE. 

When we restart one of the nodes, initially it starts off as a member; registers itself in the CLUSTER_NODE_STATUS_TABLE (so now the table has 3 entries) and then immediately elects it self as the coordinator. Although this node became the coordinator, it will only start up clean up task after one second (and after that, ever second it will happen; One second is the default time as defined in deployment.yaml (cluster.config > strategyConfig > heartbeatInterval))

Problem is, before that one second passes away (before cleaning the CLUSTER_NODE_STATUS_TABLE) , the HA manager starts and looks at the CLUSTER_NODE_STATUS_TABLE and complains that it has 3 entries hence we see below error

```
[2018-03-14 19:16:59,202] ERROR {org.eclipse.equinox.ds} - [SCR] Exception while activating instance org.wso2.carbon.stream.processor.core.internal.ServiceComponent@2e4f5bc4 of component stream-processor-core-service  java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:235)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:109)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:915)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:862)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:801)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:127)
	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:225)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:464)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:482)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:999)
	at org.wso2.carbon.kernel.internal.CarbonStartupHandler.registerCarbonServerInfoService(CarbonStartupHandler.java:55)
	at org.wso2.carbon.kernel.internal.startupresolver.StartupOrderResolver$1.run(StartupOrderResolver.java:192)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: org.wso2.carbon.stream.processor.core.ha.exception.HAModeException: More than two nodes can not be used in the minimum HA mode. Use another clustering mode, change the groupId or disable clustering.
	at org.wso2.carbon.stream.processor.core.internal.ServiceComponent.setUpClustering(ServiceComponent.java:349)
	at org.wso2.carbon.stream.processor.core.internal.ServiceComponent.start(ServiceComponent.java:203)
	... 26 more
```

**Suggested Assignees:**

**Affected Product Version:**
SP 4.0.0 2 node min HA cluster

**Comment by dilini-muthumala** [comment]
Fixed with https://github.com/wso2/carbon-coordination/pull/54 hence closing the issue
