### ISSUE TITLE
Wso2 Streaming Integrator : Error occurred while processing eventByteBufferQueue

### ISSUE THREAD

**Issue by zzakir** [wso2/carbon-analytics#1782]
**Description:**

I have two nodes of wso2-si streaming integrator (7.0.0) with high availability enabled. I see following error on active node of cluster.

please advise what is causing following issue..

ERROR {org.wso2.carbon.streaming.integrator.core.ha.tcp.EventSyncServer} - Error occurred while processing eventByteBufferQueue null java.nio.BufferUnderflowException
        at java.nio.HeapByteBuffer.get(HeapByteBuffer.java:151)
        at java.nio.ByteBuffer.get(ByteBuffer.java:715)
        at org.wso2.carbon.streaming.integrator.core.util.BinaryMessageConverterUtil.getString(BinaryMessageConverterUtil.java:108)
        at org.wso2.carbon.streaming.integrator.core.ha.tcp.SiddhiEventConverter.toObjectArray(SiddhiEventConverter.java:83)
        at org.wso2.carbon.streaming.integrator.core.ha.tcp.SiddhiEventConverter.getEvent(SiddhiEventConverter.java:62)
        at org.wso2.carbon.streaming.integrator.core.event.queue.EventListMapManager.parseMessage(EventListMapManager.java:147)
        at org.wso2.carbon.streaming.integrator.core.ha.tcp.EventSyncServer$EventBufferExtractor.run(EventSyncServer.java:149)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by chuwelee** [comment]
I encounter the same issue.  Anybody has solution to resolve it?

**Comment by zzakir** [comment]
I stopped using the inbuilt high availability because of this and other stability issues. I am using 2 separate instances of wso2 and used mqtt shared subscriptions to achieve high availability.

**Comment by chuwelee** [comment]
> I stopped using the inbuilt high availability because of this and other stability issues. I am using 2 separate instances of wso2 and used mqtt shared subscriptions to achieve high availability.

Thanks your reply. I wasted too much time to try fixing this bug. Now i give up. I have another question : Does the Wso2 SI developing team know this obviously bug?

**Comment by chuwelee** [comment]
> I stopped using the inbuilt high availability because of this and other stability issues. I am using 2 separate instances of wso2 and used mqtt shared subscriptions to achieve high availability.

And thanks your suggestion. We decide to use kafka to achieve re-balance & HA architechture.

**Comment by zzakir** [comment]
You are welcome. Their development team should know about this especially if there is an open issue here.

**Comment by zzakir** [comment]
Also we have decided to stop using wso2 because they changed the license in a minor release. It is no longer under Apache License 2.0. From version 7.0.2 onwards the License is "WSO2 Software License Agreement" which is paid unless it is for a non commercial use. Till version 7.0.1 it was under Apache License 2.0. So we decided that it is no longer viable to use it.
