### ISSUE TITLE
Unable to build `carbon-analytics` with `node v12.14.0` and `npm 7.4.3`

### ISSUE THREAD

**Issue by senthuran16** [wso2/carbon-analytics#1975]
**Description:**
$subject, fails with:
```
[INFO] ----< org.wso2.carbon.analytics:org.wso2.carbon.business.rules.web >----
[INFO] Building Business Rules Web Component 3.0.59-SNAPSHOT            [14/47]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- exec-maven-plugin:1.5.0:exec (npm install rimraf (clean)) @ org.wso2.carbon.business.rules.web ---
npm ERR! code 1
npm ERR! path /Users/senthuran/Desktop/beta-dependency-upgrade/repo/carbon-analytics/components/org.wso2.carbon.business.rules.web/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh -c node scripts/build.js
npm ERR! Building: /Users/senthuran/.nvm/versions/node/v12.14.0/bin/node /Users/senthuran/Desktop/beta-dependency-upgrade/repo/carbon-analytics/components/org.wso2.carbon.business.rules.web/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/Users/senthuran/.nvm/versions/node/v12.14.0/bin/node',
npm ERR! gyp verb cli   '/Users/senthuran/Desktop/beta-dependency-upgrade/repo/carbon-analytics/components/org.wso2.carbon.business.rules.web/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.6.2
npm ERR! gyp info using node@12.14.0 | darwin | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (/Users/senthuran/Desktop/beta-dependency-upgrade/repo/carbon-analytics/components/org.wso2.carbon.business.rules.web/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/Users/senthuran/Desktop/beta-dependency-upgrade/repo/carbon-analytics/components/org.wso2.carbon.business.rules.web/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/Users/senthuran/Desktop/beta-dependency-upgrade/repo/carbon-analytics/components/org.wso2.carbon.business.rules.web/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /Users/senthuran/Desktop/beta-dependency-upgrade/repo/carbon-analytics/components/org.wso2.carbon.business.rules.web/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /Users/senthuran/Desktop/beta-dependency-upgrade/repo/carbon-analytics/components/org.wso2.carbon.business.rules.web/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /Users/senthuran/Desktop/beta-dependency-upgrade/repo/carbon-analytics/components/org.wso2.carbon.business.rules.web/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:158:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (/Users/senthuran/Desktop/beta-dependency-upgrade/repo/carbon-analytics/components/org.wso2.carbon.business.rules.web/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/Users/senthuran/Desktop/beta-dependency-upgrade/repo/carbon-analytics/components/org.wso2.carbon.business.rules.web/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/Users/senthuran/Desktop/beta-dependency-upgrade/repo/carbon-analytics/components/org.wso2.carbon.business.rules.web/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /Users/senthuran/Desktop/beta-dependency-upgrade/repo/carbon-analytics/components/org.wso2.carbon.business.rules.web/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /Users/senthuran/Desktop/beta-dependency-upgrade/repo/carbon-analytics/components/org.wso2.carbon.business.rules.web/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /Users/senthuran/Desktop/beta-dependency-upgrade/repo/carbon-analytics/components/org.wso2.carbon.business.rules.web/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:158:21) {
npm ERR! gyp verb `which` failed   stack: 'Error: not found: python2\n' +
npm ERR! gyp verb `which` failed     '    at getNotFoundError (/Users/senthuran/Desktop/beta-dependency-upgrade/repo/carbon-analytics/components/org.wso2.carbon.business.rules.web/node_modules/which/which.js:13:12)\n' +
npm ERR! gyp verb `which` failed     '    at F (/Users/senthuran/Desktop/beta-dependency-upgrade/repo/carbon-analytics/components/org.wso2.carbon.business.rules.web/node_modules/which/which.js:68:19)\n' +
npm ERR! gyp verb `which` failed     '    at E (/Users/senthuran/Desktop/beta-dependency-upgrade/repo/carbon-analytics/components/org.wso2.carbon.business.rules.web/node_modules/which/which.js:80:29)\n' +
npm ERR! gyp verb `which` failed     '    at /Users/senthuran/Desktop/beta-dependency-upgrade/repo/carbon-analytics/components/org.wso2.carbon.business.rules.web/node_modules/which/which.js:89:16\n' +
npm ERR! gyp verb `which` failed     '    at /Users/senthuran/Desktop/beta-dependency-upgrade/repo/carbon-analytics/components/org.wso2.carbon.business.rules.web/node_modules/isexe/index.js:42:5\n' +
npm ERR! gyp verb `which` failed     '    at /Users/senthuran/Desktop/beta-dependency-upgrade/repo/carbon-analytics/components/org.wso2.carbon.business.rules.web/node_modules/isexe/mode.js:8:5\n' +
npm ERR! gyp verb `which` failed     '    at FSReqCallback.oncomplete (fs.js:158:21)',
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` succeeded python /usr/bin/python
npm ERR! gyp verb check python version `/usr/bin/python -c "import platform; print(platform.python_version());"` returned: "2.7.16\n"
npm ERR! gyp verb get node dir no --target version specified, falling back to host node version: 12.14.0
npm ERR! gyp verb command install [ '12.14.0' ]
npm ERR! gyp verb install input version string "12.14.0"
npm ERR! gyp verb install installing version: 12.14.0
npm ERR! gyp verb install --ensure was passed, so won't reinstall if already installed
npm ERR! gyp verb install version is already installed, need to check "installVersion"
npm ERR! gyp verb got "installVersion" 9
npm ERR! gyp verb needs "installVersion" 9
npm ERR! gyp verb install version is good
npm ERR! gyp verb get node dir target node version installed: 12.14.0
npm ERR! gyp verb build dir attempting to create "build" dir: /Users/senthuran/Desktop/beta-dependency-upgrade/repo/carbon-analytics/components/org.wso2.carbon.business.rules.web/node_modules/node-sass/build
npm ERR! gyp verb build dir "build" dir needed to be created? /Users/senthuran/Desktop/beta-dependency-upgrade/repo/carbon-analytics/components/org.wso2.carbon.business.rules.web/node_modules/node-sass/build
npm ERR! gyp verb build/config.gypi creating config file
npm ERR! gyp verb build/config.gypi writing out config file: /Users/senthuran/Desktop/beta-dependency-upgrade/repo/carbon-analytics/components/org.wso2.carbon.business.rules.web/node_modules/node-sass/build/config.gypi
npm ERR! gyp verb config.gypi checking for gypi file: /Users/senthuran/Desktop/beta-dependency-upgrade/repo/carbon-analytics/components/org.wso2.carbon.business.rules.web/node_modules/node-sass/config.gypi
npm ERR! gyp verb common.gypi checking for gypi file: /Users/senthuran/Desktop/beta-dependency-upgrade/repo/carbon-analytics/components/org.wso2.carbon.business.rules.web/node_modules/node-sass/common.gypi
npm ERR! gyp verb gyp gyp format was not specified; forcing "make"
npm ERR! gyp info spawn /usr/bin/python
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/senthuran/Desktop/beta-dependency-upgrade/repo/carbon-analytics/components/org.wso2.carbon.business.rules.web/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/senthuran/Desktop/beta-dependency-upgrade/repo/carbon-analytics/components/org.wso2.carbon.business.rules.web/node_modules/node-sass/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/senthuran/Desktop/beta-dependency-upgrade/repo/carbon-analytics/components/org.wso2.carbon.business.rules.web/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/senthuran/.node-gyp/12.14.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/senthuran/.node-gyp/12.14.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/senthuran/Desktop/beta-dependency-upgrade/repo/carbon-analytics/components/org.wso2.carbon.business.rules.web/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/senthuran/.node-gyp/12.14.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/senthuran/Desktop/beta-dependency-upgrade/repo/carbon-analytics/components/org.wso2.carbon.business.rules.web/node_modules/node-sass',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
npm ERR!
npm ERR! xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
npm ERR!
npm ERR! Traceback (most recent call last):
npm ERR!   File "/Users/senthuran/Desktop/beta-dependency-upgrade/repo/carbon-analytics/components/org.wso2.carbon.business.rules.web/node_modules/node-gyp/gyp/gyp_main.py", line 16, in <module>
npm ERR!     sys.exit(gyp.script_main())
npm ERR!   File "/Users/senthuran/Desktop/beta-dependency-upgrade/repo/carbon-analytics/components/org.wso2.carbon.business.rules.web/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 545, in script_main
npm ERR!     return main(sys.argv[1:])
npm ERR!   File "/Users/senthuran/Desktop/beta-dependency-upgrade/repo/carbon-analytics/components/org.wso2.carbon.business.rules.web/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 538, in main
npm ERR!     return gyp_main(args)
npm ERR!   File "/Users/senthuran/Desktop/beta-dependency-upgrade/repo/carbon-analytics/components/org.wso2.carbon.business.rules.web/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 523, in gyp_main
npm ERR!     generator.GenerateOutput(flat_list, targets, data, params)
npm ERR!   File "/Users/senthuran/Desktop/beta-dependency-upgrade/repo/carbon-analytics/components/org.wso2.carbon.business.rules.web/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 2170, in GenerateOutput
npm ERR!     part_of_all=qualified_target in needed_targets)
npm ERR!   File "/Users/senthuran/Desktop/beta-dependency-upgrade/repo/carbon-analytics/components/org.wso2.carbon.business.rules.web/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 795, in Write
npm ERR!     self.Pchify))
npm ERR!   File "/Users/senthuran/Desktop/beta-dependency-upgrade/repo/carbon-analytics/components/org.wso2.carbon.business.rules.web/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 1190, in WriteSources
npm ERR!     cflags = self.xcode_settings.GetCflags(configname)
npm ERR!   File "/Users/senthuran/Desktop/beta-dependency-upgrade/repo/carbon-analytics/components/org.wso2.carbon.business.rules.web/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 551, in GetCflags
npm ERR!     archs = self.GetActiveArchs(self.configname)
npm ERR!   File "/Users/senthuran/Desktop/beta-dependency-upgrade/repo/carbon-analytics/components/org.wso2.carbon.business.rules.web/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 420, in GetActiveArchs
npm ERR!     xcode_archs_default = GetXcodeArchsDefault()
npm ERR!   File "/Users/senthuran/Desktop/beta-dependency-upgrade/repo/carbon-analytics/components/org.wso2.carbon.business.rules.web/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 118, in GetXcodeArchsDefault
npm ERR!     xcode_version, _ = XcodeVersion()
npm ERR!   File "/Users/senthuran/Desktop/beta-dependency-upgrade/repo/carbon-analytics/components/org.wso2.carbon.business.rules.web/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1265, in XcodeVersion
npm ERR!     version = re.match(r'(\d\.\d\.?\d*)', version).groups()[0]
npm ERR! AttributeError: 'NoneType' object has no attribute 'groups'
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/Users/senthuran/Desktop/beta-dependency-upgrade/repo/carbon-analytics/components/org.wso2.carbon.business.rules.web/node_modules/node-gyp/lib/configure.js:336:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
npm ERR! gyp ERR! System Darwin 18.7.0
npm ERR! gyp ERR! command "/Users/senthuran/.nvm/versions/node/v12.14.0/bin/node" "/Users/senthuran/Desktop/beta-dependency-upgrade/repo/carbon-analytics/components/org.wso2.carbon.business.rules.web/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd /Users/senthuran/Desktop/beta-dependency-upgrade/repo/carbon-analytics/components/org.wso2.carbon.business.rules.web/node_modules/node-sass
npm ERR! gyp ERR! node -v v12.14.0
npm ERR! gyp ERR! node-gyp -v v3.6.2
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/senthuran/.npm/_logs/2022-03-14T06_04_43_477Z-debug.log
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:764)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:711)
    at org.codehaus.mojo.exec.ExecMojo.execute (ExecMojo.java:289)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:954)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] WSO2 Carbon Analytics - Parent 3.0.59-SNAPSHOT ..... SUCCESS [  3.351 s]
[INFO] WSO2 Streaming Integrator - Common ................. SUCCESS [ 44.865 s]
[INFO] WSO2 Carbon - Siddhi Metrics Core .................. SUCCESS [01:30 min]
[INFO] WSO2 Streaming Integrator - Interceptors ........... SUCCESS [01:08 min]
[INFO] WSO2 Streaming Integrator - Core ................... SUCCESS [05:17 min]
[INFO] WSO2 Streaming Integrator - Event Simulator ........ SUCCESS [04:40 min]
[INFO] WSO2 Carbon - Editor Log Appender .................. SUCCESS [ 28.066 s]
[INFO] WSO2 Streaming Integrator - Editor Core ............ SUCCESS [19:43 min]
[INFO] WSO2 Siddhi Extensions Installer - CLI ............. SUCCESS [ 10.294 s]
[INFO] WSO2 Streaming Integrator - Siddhi Extensions Installer Core SUCCESS [ 28.640 s]
[INFO] WSO2 Streaming Integrator - Siddhi Error Handler Core SUCCESS [ 23.294 s]
[INFO] WSO2 Streaming Integrator - Business Rules Template Editor SUCCESS [09:07 min]
[INFO] WSO2 Streaming Integrator - Business Rules ......... SUCCESS [ 37.512 s]
[INFO] Business Rules Web Component ....................... FAILURE [01:05 min]
[INFO] WSO2 Carbon - SP Coordination Listener ............. SKIPPED
[INFO] org.wso2.carbon.streaming.integrator.statistics .... SKIPPED
[INFO] WSO2 Streaming Integrator - Siddhi Store Query REST API SKIPPED
[INFO] WSO2 Streaming Integrator - Authentication API ..... SKIPPED
[INFO] WSO2 Carbon - Permission Provider .................. SKIPPED
[INFO] WSO2 Carbon - Data Provider Module ................. SKIPPED
[INFO] WSO2 Streaming Integrator - Health Check REST API .. SKIPPED
[INFO] org.wso2.siddhi.parser ............................. SKIPPED
[INFO] WSO2 Streaming Integrator - Core Feature ........... SKIPPED
[INFO] WSO2 Streaming Integrator - Common Feature ......... SKIPPED
[INFO] WSO2 Streaming Integrator - Event Simulator Feature  SKIPPED
[INFO] WSO2 Streaming Integrator - Siddhi Editor Feature .. SKIPPED
[INFO] WSO2 Streaming Integrator - Siddhi Extensions Installer Feature SKIPPED
[INFO] WSO2 Streaming Integrator - Siddhi Error Handler Feature SKIPPED
[INFO] WSO2 Streaming Integrator - Business Rules Template Editor Feature SKIPPED
[INFO] WSO2 Streaming Integrator - Business Rules Core Feature SKIPPED
[INFO] WSO2 Streaming Integrator Business Rule Web Component SKIPPED
[INFO] WSO2 Streaming Integrator - Siddhi Feature ......... SKIPPED
[INFO] WSO2 Carbon - Siddhi Metrics Core .................. SKIPPED
[INFO] WSO2 Carbon - SP Coordination Listener feature ..... SKIPPED
[INFO] WSO2 Streaming Integrator - Statistics Feature ..... SKIPPED
[INFO] WSO2 Streaming Integrator - Siddhi Store Query REST API Feature SKIPPED
[INFO] WSO2 Streaming Integrator - Authentication API Feature SKIPPED
[INFO] WSO2 Data  Feature ................................. SKIPPED
[INFO] WSO2 Carbon - Data Provider - Feature .............. SKIPPED
[INFO] WSO2 Streaming Integrator - Interceptor Feature .... SKIPPED
[INFO] WSO2 Streaming Integrator - Heath Check Core API Feature SKIPPED
[INFO] WSO2 Streaming Integrator - Store Query REST API Feature SKIPPED
[INFO] WSO2 Carbon Analytics - Streaming Integrator Tooling Test Distribution SKIPPED
[INFO] WSO2 Carbon Analytics - Streaming Integrator Test Distribution SKIPPED
[INFO] WSO2 Carbon Analytics Streaming Integrator - OSGi Tests SKIPPED
[INFO] WSO2 Carbon Analytics Tooling - OSGi Tests ......... SKIPPED
[INFO] Carbon Analytics Tests Coverage Report Aggregation 3.0.59-SNAPSHOT SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 45:32 min
[INFO] Finished at: 2022-03-14T11:34:48+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.5.0:exec (npm install rimraf (clean)) on project org.wso2.carbon.business.rules.web: Command execution failed.: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :org.wso2.carbon.business.rules.web
```

**Comment by PasanT9** [comment]
Installing Python 2.x resolved the issue for me.
